### ISSUE TITLE
Syntax Error for generated code. Should remove "unless...end" with empty condition.

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.ruby#39]
![image](https://user-images.githubusercontent.com/69238381/120298072-52b3e300-c2fc-11eb-82b9-fb55e506cc7d.png)

**Comment by sarangan12** [comment]
As of February 2021, Azure Resource Management SDK for Ruby and Autorest.Ruby have entered a retirement phase and is no longer officially supported by Microsoft. Here is the complete list of packages that are affected by this. We are committed to making critical security and bug fixes for libraries in this repo until December 31, 2021. After that date, this repo will no longer be maintained.
